"""add gmail history id

Revision ID: 862f06b05b1c
Revises: 9e51bac20307
Create Date: 2026-07-09 13:12:32.536647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '862f06b05b1c'
down_revision: Union[str, Sequence[str], None] = '9e51bac20307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gmail_history_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gmail_history_id')
    # ### end Alembic commands ###
