"""add_session_metadata_to_refresh_tokens

Revision ID: e0b5377abfb5
Revises: efd11aea32c8
Create Date: 2026-07-08 21:45:53.084643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0b5377abfb5'
down_revision: Union[str, Sequence[str], None] = 'efd11aea32c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('refresh_tokens', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('refresh_tokens', sa.Column('operating_system', sa.String(length=100), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=100), nullable=True))
    op.add_column('refresh_tokens', sa.Column('user_agent', sa.String(length=500), nullable=True))
    op.add_column(
        "refresh_tokens",
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'last_used_at')
    op.drop_column('refresh_tokens', 'user_agent')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'operating_system')
    op.drop_column('refresh_tokens', 'browser')
    op.drop_column('refresh_tokens', 'device_name')
    # ### end Alembic commands ###
